from __future__ import annotations

import argparse

from research_cockpit.commands._runtime import emit_json
from research_cockpit.command_registry import (
    COMMAND_GROUP_CHOICES,
    COMMAND_STATUS_CHOICES,
    command_group_for_command,
    command_lifecycle_for_command,
    grouped_aliases_for_command,
    subcommand_for_script,
)
from research_cockpit.commands.file_schemas import file_schema_for_script
from research_cockpit.commands.update_node_fields import supported_field_names

WORKFLOW_CHOICES = ("graph", "evidence", "decision", "focus", "maintenance", "read")
GROUP_CHOICES = COMMAND_GROUP_CHOICES
STATUS_CHOICES = COMMAND_STATUS_CHOICES
STATUS_ALIASES = {"option": {"planned": "open"}}
CONFLICT_POLICY = "Truth-source mutation fails without writing if target files changed after command planning; reread context and retry."
COMPACT_COMMAND_KEYS = {
    "name",
    "canonical_name",
    "purpose",
    "command",
    "group",
    "lifecycle",
    "status",
    "aliases",
    "replacement",
    "input_modes",
    "workflow_tags",
    "mutating",
    "supports_json",
    "supports_dry_run",
    "supports_no_build",
    "supports_compact",
    "supports_build",
    "supports_watch",
    "supports_profile",
    "supports_show_diff",
    "supports_root",
    "supported_flags",
    "unsupported_flags",
    "can_batch",
    "batch_policy",
    "requires_serial_mutation",
    "conflict_policy",
    "schema_command",
    "primary_target",
    "target_aliases",
    "status_aliases",
}
SUMMARY_COMMAND_KEYS = {
    "name",
    "canonical_name",
    "purpose",
    "group",
    "status",
    "input_modes",
    "workflow_tags",
    "mutating",
    "supports_json",
    "supports_dry_run",
    "supports_no_build",
    "supports_compact",
    "supported_flags",
    "can_batch",
    "batch_policy_mode",
    "primary_target",
}
BATCH_WORKER_VERIFY_COMMANDS = [
    "research-cockpit validate --root <root> --changed-node <node_id> --json",
    "research-cockpit context --root <root> --id <node_id> --with-bootstrap --with-artifacts --compact --json",
]
BATCH_FINAL_HANDOFF_COMMANDS = [
    "research-cockpit validate --root <root> --json",
    "research-cockpit build --root <root>",
    "research-cockpit smoke --root <root> --json --progress",
]
ASSIGNMENT_SCOPE_FLAGS = ["--assignment", "--coordinator"]

WORKFLOW_TAGS_BY_COMMAND = {
    "init": ["maintenance"],
    "ui": ["read"],
    "bootstrap": ["read", "focus"],
    "validate": ["read", "maintenance", "graph"],
    "lint": ["read", "maintenance", "graph"],
    "repair-interaction-log": ["maintenance"],
    "migrate-interaction-log": ["maintenance"],
    "build": ["maintenance", "graph"],
    "smoke": ["read", "maintenance"],
    "search": ["read", "focus"],
    "suggest-next-actions": ["read", "focus"],
    "commands": ["read", "maintenance"],
    "node-context": ["read", "focus"],
    "context": ["read", "focus", "evidence"],
    "assignment-view": ["read", "evidence", "focus"],
    "option-workstream-context": ["read", "evidence"],
    "agent-session-context": ["read", "focus", "evidence"],
    "check-decision-acceptance": ["read", "decision"],
    "add-node": ["graph"],
    "apply-graph-plan": ["graph"],
    "create-workstream": ["graph"],
    "close-branch": ["graph", "maintenance"],
    "update-status": ["graph"],
    "set-focus": ["focus"],
    "set-agent-focus": ["focus"],
    "set-cursor": ["focus"],
    "sync-focus-actions": ["focus"],
    "claim-option": ["evidence", "focus"],
    "claim-workstream": ["evidence", "focus"],
    "start-agent-session": ["evidence", "focus"],
    "create-run": ["evidence"],
    "update-run": ["evidence"],
    "complete-run": ["evidence"],
    "list-runs": ["read", "evidence"],
    "active-resources": ["read", "maintenance", "evidence"],
    "worktree-audit": ["read", "maintenance", "evidence"],
    "branch-audit": ["read", "maintenance", "evidence"],
    "artifact-retention-audit": ["read", "maintenance", "evidence"],
    "maintenance-audit": ["read", "maintenance", "evidence", "focus"],
    "worktree-closeout": ["read", "maintenance", "evidence"],
    "run-context": ["read", "evidence"],
    "record-gate-result": ["evidence"],
    "ingest-gate-result": ["evidence"],
    "report-option-workstream": ["evidence"],
    "finalize-workstream": ["evidence", "focus"],
    "import-worktree-findings": ["evidence"],
    "ingest-artifact": ["evidence"],
    "artifact-records": ["read", "evidence"],
    "promote-artifact-record": ["evidence"],
    "compact-artifacts": ["maintenance", "evidence"],
    "record-finding": ["evidence"],
    "update-finding": ["evidence"],
    "create-artifact": ["evidence"],
    "link-artifact": ["evidence"],
    "complete-experiment": ["evidence"],
    "close-current-experiment": ["evidence", "focus"],
    "complete-experiments": ["evidence"],
    "create-followup-experiment": ["graph", "evidence", "focus"],
    "migrate-terminal-next-actions": ["graph", "evidence", "focus"],
    "promote-decision": ["decision"],
    "update-decision-evidence": ["decision", "evidence"],
    "update-decision-checklist": ["decision"],
    "accept-decision": ["decision"],
    "set-baseline": ["decision", "focus"],
    "update-node-fields": ["graph"],
    "update-workstream-fields": ["evidence", "graph"],
    "apply-suggestion": ["focus"],
    "update-suggestion-state": ["focus", "maintenance"],
    "cleanup-suggestion-lifecycle": ["focus", "maintenance"],
    "create-note": ["graph"],
}

SHOW_DIFF_COMMANDS = {
    "add-node",
    "apply-graph-plan",
    "close-branch",
    "cleanup-suggestion-lifecycle",
    "complete-experiment",
    "complete-experiments",
    "create-artifact",
    "create-followup-experiment",
    "migrate-terminal-next-actions",
    "create-note",
    "create-run",
    "create-workstream",
    "complete-run",
    "finalize-workstream",
    "import-worktree-findings",
    "ingest-artifact",
    "promote-artifact-record",
    "compact-artifacts",
    "ingest-gate-result",
    "link-artifact",
    "record-finding",
    "record-gate-result",
    "report-option-workstream",
    "set-agent-focus",
    "set-cursor",
    "set-baseline",
    "set-focus",
    "start-agent-session",
    "sync-focus-actions",
    "update-decision-checklist",
    "update-decision-evidence",
    "update-finding",
    "update-node-fields",
    "update-run",
    "update-workstream-fields",
    "update-suggestion-state",
    "update-status",
    "repair-interaction-log",
}


CAPABILITY_BY_COMMAND = {
    "init": "capabilities/integrations.md",
    "ui": "capabilities/ui-dashboard.md",
    "agent_bootstrap.py": "capabilities/focus-context.md",
    "validate_cockpit.py": "capabilities/troubleshooting.md",
    "lint_semantic.py": "capabilities/troubleshooting.md",
    "repair_interaction_log.py": "capabilities/troubleshooting.md",
    "migrate_interaction_log.py": "capabilities/troubleshooting.md",
    "build_dashboard.py": "capabilities/graph-state.md",
    "skill_smoke_test.py": "capabilities/integrations.md",
    "search_knowledge.py": "capabilities/focus-context.md",
    "suggest_next_actions.py": "capabilities/focus-context.md",
    "list_agent_commands.py": "capabilities/focus-context.md",
    "context.py": "capabilities/focus-context.md",
    "assignment_view.py": "capabilities/experiment-tracking.md",
    "node_context.py": "capabilities/focus-context.md",
    "option_workstream_context.py": "capabilities/experiment-tracking.md",
    "agent_session_context.py": "capabilities/focus-context.md",
    "check_decision_acceptance.py": "capabilities/decision-adr.md",
    "add_node.py": "capabilities/node-management.md",
    "apply_graph_plan.py": "capabilities/node-management.md",
    "create_workstream.py": "capabilities/node-management.md",
    "close_branch.py": "capabilities/node-management.md",
    "update_status.py": "capabilities/node-management.md",
    "set_focus.py": "capabilities/focus-context.md",
    "set_agent_focus.py": "capabilities/focus-context.md",
    "set_cursor.py": "capabilities/focus-context.md",
    "sync_focus_actions.py": "capabilities/focus-context.md",
    "claim_option.py": "capabilities/experiment-tracking.md",
    "claim_workstream.py": "capabilities/experiment-tracking.md",
    "start_agent_session.py": "capabilities/experiment-tracking.md",
    "create_run.py": "capabilities/experiment-tracking.md",
    "update_run.py": "capabilities/experiment-tracking.md",
    "complete_run.py": "capabilities/experiment-tracking.md",
    "list_runs.py": "capabilities/experiment-tracking.md",
    "active_resources.py": "capabilities/maintenance.md",
    "worktree_audit.py": "capabilities/maintenance.md",
    "branch_audit.py": "capabilities/maintenance.md",
    "artifact_retention_audit.py": "capabilities/maintenance.md",
    "maintenance_audit.py": "capabilities/maintenance.md",
    "worktree_closeout.py": "capabilities/maintenance.md",
    "run_context.py": "capabilities/experiment-tracking.md",
    "record_gate_result.py": "capabilities/experiment-tracking.md",
    "ingest_gate_result.py": "capabilities/experiment-tracking.md",
    "report_option_workstream.py": "capabilities/experiment-tracking.md",
    "finalize_workstream.py": "capabilities/experiment-tracking.md",
    "import_worktree_findings.py": "capabilities/experiment-tracking.md",
    "ingest_artifact.py": "capabilities/experiment-tracking.md",
    "list_artifact_records.py": "capabilities/experiment-tracking.md",
    "promote_artifact_record.py": "capabilities/experiment-tracking.md",
    "compact_artifacts.py": "capabilities/maintenance.md",
    "record_finding.py": "capabilities/experiment-tracking.md",
    "update_finding.py": "capabilities/experiment-tracking.md",
    "create_artifact.py": "capabilities/experiment-tracking.md",
    "link_artifact.py": "capabilities/experiment-tracking.md",
    "complete_experiment.py": "capabilities/experiment-tracking.md",
    "close_current_experiment.py": "capabilities/experiment-tracking.md",
    "complete_experiments.py": "capabilities/experiment-tracking.md",
    "create_followup_experiment.py": "capabilities/experiment-tracking.md",
    "migrate_terminal_next_actions.py": "capabilities/experiment-tracking.md",
    "promote_decision.py": "capabilities/decision-adr.md",
    "update_decision_evidence.py": "capabilities/decision-adr.md",
    "update_decision_checklist.py": "capabilities/decision-adr.md",
    "accept_decision.py": "capabilities/decision-adr.md",
    "set_baseline.py": "capabilities/focus-context.md",
    "update_node_fields.py": "capabilities/node-management.md",
    "update_workstream_fields.py": "capabilities/experiment-tracking.md",
    "apply_suggestion.py": "capabilities/node-management.md",
    "update_suggestion_state.py": "capabilities/node-management.md",
    "cleanup_suggestion_lifecycle.py": "capabilities/node-management.md",
    "create_note.py": "capabilities/node-management.md",
}




COMMANDS: list[dict[str, object]] = [
    {
        "name": "init",
        "purpose": "Initialize a project-local research_cockpit state directory from a template.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_build": True,
        "recommended_when": "Start a new research repo before recording project-specific state.",
    },
    {
        "name": "ui",
        "purpose": "Launch the Streamlit researcher dashboard for a data root.",
        "mutating": False,
        "supports_json": False,
        "supports_dry_run": False,
        "supports_no_build": False,
        "recommended_when": "Inspect graph state, saved views, decisions, search, and data health interactively.",
    },
    {
        "name": "agent_bootstrap.py",
        "purpose": "Inspect validation status, focus, context paths, suggestions, search summary, git state, and optional agent scope.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_build": True,
        "extra_supported_flags": ["--agent", "--assignment", "--option", "--coordinator"],
        "recommended_when": "Use for assignment-scoped startup or unknown/global triage; known-node tasks should start with compact context.",
    },
    {
        "name": "validate_cockpit.py",
        "purpose": "Validate YAML nodes, focus state, edges, and lifecycle structure.",
        "mutating": False,
        "supports_json": True,
        "supports_compact": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "extra_supported_flags": ["--strict-lifecycle", "--changed-node", "--changed-file", "--changed-files", "--changed-record", "--include-affected-ids"],
        "recommended_when": "Use changed flags after small worker edits; use full validation for coordinator or final gates.",
    },
    {
        "name": "lint_semantic.py",
        "purpose": "Warn about stale but structurally valid research state.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "required_flags": ["--semantic"],
        "extra_supported_flags": ["--semantic"],
        "fields_supported": ["semantic"],
        "recommended_when": "Check for done focus nodes, stale agent focus, and next action drift.",
    },
    {
        "name": "repair_interaction_log.py",
        "purpose": "Repair schema-damaged interaction log events after validation reports audit log damage.",
        "mutating": True,
        "writes_truth_source": False,
        "writes_generated_files": False,
        "rebuild_default": False,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": False,
        "recommended_when": "Recover from non-mapping interaction log events without hand-editing YAML.",
    },
    {
        "name": "migrate_interaction_log.py",
        "purpose": "Plan or activate the append-only JSONL interaction event backend while preserving legacy YAML.",
        "mutating": True,
        "writes_truth_source": False,
        "writes_generated_files": False,
        "rebuild_default": False,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": False,
        "extra_supported_flags": ["--execute"],
        "recommended_when": "Run dry-run first for large legacy interaction logs, then execute once after reviewing counts and checksums.",
    },
    {
        "name": "build_dashboard.py",
        "purpose": "Regenerate dashboard and context JSON from YAML truth source.",
        "mutating": True,
        "writes_truth_source": False,
        "writes_dashboard": True,
        "writes_generated_files": True,
        "rebuild_default": True,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_watch": True,
        "supports_profile": True,
        "extra_supported_flags": ["--skip-resource-search", "--affected", "--id"],
        "recommended_when": "Refresh generated context after YAML changes.",
    },
    {
        "name": "skill_smoke_test.py",
        "purpose": "Run a read-only compact agent workflow smoke test, with an opt-in full workflow.",
        "mutating": False,
        "writes_generated_files": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "extra_supported_flags": ["--full", "--scope", "--id", "--progress"],
        "recommended_when": "Use --scope changed --id after one node edit; use default compact smoke for coordinator/root checks.",
    },
    {
        "name": "search_knowledge.py",
        "purpose": "Search YAML nodes, notes, and indexed local text resources.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "extra_supported_flags": ["--limit", "--source", "--node-type", "--focus-only"],
        "recommended_when": "Find relevant research context before editing.",
    },
    {
        "name": "suggest_next_actions.py",
        "purpose": "List active or inactive action suggestions.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "extra_supported_flags": ["--limit", "--kind", "--focus-only", "--include-inactive", "--state"],
        "recommended_when": "Decide what work should happen next.",
    },
    {
        "name": "list_agent_commands.py",
        "purpose": "List command capabilities and workflow tags for agent command selection.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "supports_root": False,
        "extra_supported_flags": ["--summary-only"],
        "recommended_when": "Choose the shortest safe command for a workflow.",
    },
    {
        "name": "node_context.py",
        "purpose": "Read a single node onboarding context with parent chain, blockers, evidence, and safe next commands.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "recommended_when": "Start work from a specific research node id.",
    },
    {
        "name": "context.py",
        "purpose": "Read compact combined context for one known node, optionally including bootstrap and artifacts.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "safe_in_plan_mode": True,
        "recommended_when": "Continue work from a known option or experiment without reading several context packs.",
    },
    {
        "name": "assignment_view.py",
        "purpose": "List high-priority queued/running experiment assignments with dependencies, owner, artifacts, and next actions.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "fields_supported": [
            "status",
            "priority",
            "order",
            "rank",
            "owner",
            "ready_for_agent",
            "depends_on",
            "blocked_by",
            "handoff_context",
            "linked_artifacts",
            "next_actions",
        ],
        "recommended_when": "Choose a low-ambiguity experiment task for a downstream agent.",
    },
    {
        "name": "option_workstream_context.py",
        "purpose": "Read context for one option workstream, including recursive child problems, options, experiments, and evidence.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "primary_target": "--id",
        "target_parameter": "--option",
        "target_aliases": ["--id"],
        "recommended_when": "Before an agent follows an option branch.",
    },
    {
        "name": "agent_session_context.py",
        "purpose": "Read the canonical root, assignment metadata, assignment cursor, and compact option context for one worker assignment.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "primary_target": "--assignment",
        "target_aliases": ["--agent", "--option"],
        "extra_supported_flags": ["--assignment", "--agent", "--option"],
        "recommended_when": "Start or resume a downstream agent from its assignment-scoped handoff.",
    },
    {
        "name": "check_decision_acceptance.py",
        "purpose": "Check whether a decision satisfies acceptance quality gates.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "recommended_when": "Before accepting a proposed decision.",
    },
    {
        "name": "add_node.py",
        "purpose": "Create a new research node YAML file.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "recommended_when": "Add a stage, problem, option, experiment, decision, or long-lived artifact.",
    },
    {
        "name": "apply_graph_plan.py",
        "purpose": "Apply a validated YAML graph update plan in one batched mutation.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "can_batch": True,
        "status_aliases": STATUS_ALIASES,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        **file_schema_for_script("apply_graph_plan.py"),
        "recommended_when": "Create or update several nodes without repeated rebuilds.",
    },
    {
        "name": "create_workstream.py",
        "purpose": "Create a problem, active option, experiments, and follow-up options from a workstream YAML file.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "can_batch": True,
        "fields_supported": ["question", "hypothesis", "summary", "tags", "success_criteria", "metrics", "next_actions"],
        "status_aliases": STATUS_ALIASES,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        **file_schema_for_script("create_workstream.py"),
        "hierarchy_guidance": (
            "Use create-workstream to create an option -> problem -> option -> experiment branch. "
            "For derived worktree follow-up, set problem.parent to the inherited option id."
        ),
        "recommended_when": "Start a new research branch from a structured workstream plan.",
    },
    {
        "name": "close_branch.py",
        "purpose": "Safely close active downstream work before marking a problem or option terminal.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "can_batch": True,
        "fields_supported": ["downstream_status=parked", "include_experiments"],
        "extra_supported_flags": ["--include-experiments", "--downstream-status"],
        "recommended_when": "Clear active descendants reported by terminal_parent_has_active_descendants before closing a branch.",
    },
    {
        "name": "update_status.py",
        "purpose": "Update a node status and optional summaries.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["status", "summary", "result_summary"],
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "recommended_when": "Move experiment/problem/option state forward without accepting a decision.",
    },
    {
        "name": "set_focus.py",
        "purpose": "Update coordinator/UI focus and compatibility current_state focus fields.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "fields_supported": ["current_stage", "current_problem", "current_option", "current_focus_node", "current_focus_path", "current_hypothesis", "open_risks", "next_actions"],
        "recommended_when": "Change coordinator or human dashboard selection; worker agents should use set-cursor.",
    },
    {
        "name": "set_agent_focus.py",
        "purpose": "Legacy compatibility: update current_state.agent_focuses without changing coordinator focus.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "fields_supported": ["agent_focuses", "current_focus_node", "current_focus_path", "current_option", "next_actions"],
        "recommended_when": "Only for older roots that still use per-agent focus; new worker sessions should use set-cursor with --assignment.",
    },
    {
        "name": "set_cursor.py",
        "purpose": "Update one assignment-local worker cursor without changing coordinator focus.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "supports_show_diff": True,
        "primary_target": "--assignment",
        "target_aliases": ["--node"],
        "extra_supported_flags": ["--assignment", "--node", "--next-action"],
        "fields_supported": ["assignment.current_node", "assignment.next_actions"],
        "recommended_when": "Move a downstream agent within its assigned branch after reading assignment-scoped bootstrap.",
    },
    {
        "name": "sync_focus_actions.py",
        "purpose": "Replace or append coordinator/global next_actions from a node's next_actions.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "recommended_when": "Keep coordinator dashboard actions aligned with the selected focus node; worker agents should use assignment next_actions.",
    },
    {
        "name": "claim_option.py",
        "purpose": "Claim an option for a single active agent workstream.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Start agent work on one candidate option branch.",
    },
    {
        "name": "claim_workstream.py",
        "purpose": "Alias for claim-option when the intent is claiming an option workstream.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Claim a workstream while using terminology aligned with parallel agents.",
    },
    {
        "name": "start_agent_session.py",
        "purpose": "Create an optional git worktree and record an agent session on a canonical option workstream.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "extra_supported_flags": [
            "--option",
            "--agent",
            "--assignment",
            "--assignment-id",
            "--label",
            "--objective",
            "--branch",
            "--worktree",
            "--base",
            "--create-worktree",
            "--force",
            "--sparse",
            "--sparse-profile",
        ],
        "fields_supported": [
            "agent_id",
            "assignment_id",
            "agent_workstream.session_id",
            "owner",
            "objective",
            "git_branch",
            "worktree_label",
            "launch_env",
            "startup_command",
            "sparse_worktree.command_plan",
        ],
        "recommended_when": "Launch a downstream agent on a branch while keeping Research Cockpit writes in the main root.",
    },
    {
        "name": "create_run.py",
        "purpose": "Create a run/job record for one concrete experiment execution.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": [
            "--id",
            "--experiment",
            "--experiment-id",
            "--status",
            *ASSIGNMENT_SCOPE_FLAGS,
            "--resources-json",
            "--resources-file",
            "--output-retention-json",
            "--output-retention-file",
        ],
        "fields_supported": [
            "run_id",
            "status",
            "experiment_id",
            "started_at",
            "finished_at",
            "launcher",
            "command",
            "tmux_session",
            "pid",
            "log_root",
            "output_root",
            "monitor_command",
            "stop_command",
            "progress_file",
            "config_file",
            "resources",
            "output_retention",
        ],
        "recommended_when": "Register a long-running run before launching or immediately after launch.",
    },
    {
        "name": "update_run.py",
        "purpose": "Update status or operational metadata for an existing run/job record.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": [
            "--id",
            "--experiment",
            "--experiment-id",
            "--status",
            *ASSIGNMENT_SCOPE_FLAGS,
            "--resources-json",
            "--resources-file",
            "--output-retention-json",
            "--output-retention-file",
        ],
        "fields_supported": [
            "status",
            "experiment_id",
            "started_at",
            "finished_at",
            "launcher",
            "command",
            "tmux_session",
            "pid",
            "log_root",
            "output_root",
            "monitor_command",
            "stop_command",
            "progress_file",
            "config_file",
            "resources",
            "output_retention",
        ],
        "recommended_when": "Refresh run status, progress file, logs, process id, or stop command without editing YAML.",
    },
    {
        "name": "complete_run.py",
        "purpose": "Close a run directly or apply a structured transactional run closeout.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": [
            "--file",
            "--print-schema",
            *ASSIGNMENT_SCOPE_FLAGS,
            "--resources-json",
            "--resources-file",
            "--output-retention-json",
            "--output-retention-file",
        ],
        "fields_supported": [
            "status",
            "finished_at",
            "progress_file",
            "log_root",
            "output_root",
            "monitor_command",
            "stop_command",
            "resources",
            "output_retention",
        ],
        **file_schema_for_script("complete_run.py"),
        "recommended_when": "Use --file to close a run, gates, artifact record, finding, and next actions in one transaction.",
    },
    {
        "name": "list_runs.py",
        "purpose": "List run/job records, optionally filtered by experiment or status.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "fields_supported": ["status", "experiment_id"],
        "recommended_when": "Inspect active, queued, or completed concrete experiment runs.",
    },
    {
        "name": "active_resources.py",
        "purpose": "List active run resource claims such as tmux sessions, pids, ports, GPUs, logs, and output roots.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": False,
        "extra_supported_flags": ["--include-terminal"],
        "fields_supported": [
            "status",
            "experiment_id",
            "resources",
            "tmux_session",
            "pid",
            "log_root",
            "output_root",
            "progress_file",
            "config_file",
        ],
        "recommended_when": "Before launching, reusing, or cleaning up downstream agent runs and scarce local resources.",
    },
    {
        "name": "worktree_audit.py",
        "purpose": "Inspect git worktrees and join them to assignment, workstream, and run state.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": False,
        "extra_supported_flags": ["--repo", "--include-nested"],
        "fields_supported": [
            "branch",
            "label",
            "assignment_ids",
            "option_workstream_node_ids",
            "active_workstream_node_ids",
            "active_node_ids",
            "run_statuses",
            "blockers",
        ],
        "recommended_when": "Before removing, reusing, or investigating agent worktrees.",
    },
    {
        "name": "branch_audit.py",
        "purpose": "Classify local git branches by checkout, merge, Research Cockpit linkage, and cleanup state.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": False,
        "extra_supported_flags": ["--repo", "--base"],
        "fields_supported": [
            "name",
            "branch_class",
            "checked_out",
            "merged",
            "assignment_ids",
            "option_workstream_node_ids",
            "active_workstream_node_ids",
            "evidence_count",
            "recommended_action",
        ],
        "recommended_when": "Before deleting, archiving, or promoting temporary local branches.",
    },
    {
        "name": "artifact_retention_audit.py",
        "purpose": "Report artifact path sizes, retention metadata, active resource blockers, and cleanup candidates.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": False,
        "extra_supported_flags": ["--repo", "--min-size-gb", "--max-files"],
        "fields_supported": [
            "artifact_id",
            "path",
            "retention_class",
            "total_size_bytes",
            "large",
            "missing_retention",
            "active_resource_references",
            "linked_references",
            "active_assignment_references",
            "cleanup_candidate",
        ],
        "recommended_when": "Before deleting or archiving large artifact payloads.",
    },
    {
        "name": "maintenance_audit.py",
        "purpose": "Aggregate active resources, worktrees, branches, artifact retention, blockers, and cleanup guidance.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": False,
        "extra_supported_flags": ["--repo", "--base", "--min-size-gb", "--max-files"],
        "fields_supported": [
            "active_assignments",
            "running_runs",
            "active_resources",
            "worktree_candidates",
            "branch_candidates",
            "blocked_worktrees",
            "blocked_branches",
            "large_artifact_candidates",
            "large_output_candidates",
            "dashboard_performance_warnings",
            "unsafe_cleanup_blockers",
            "recommended_next_actions",
        ],
        "recommended_when": "Before repository cleanup, branch cleanup, or worktree closeout.",
    },
    {
        "name": "worktree_closeout.py",
        "purpose": "Generate a dry-run closeout plan for one git worktree.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": False,
        "supports_compact": True,
        "extra_supported_flags": [
            "--repo",
            "--worktree",
            "--classification",
            "--base",
            "--include-nested",
            "--min-size-gb",
            "--max-files",
        ],
        "fields_supported": [
            "classification",
            "target_worktree",
            "blockers",
            "rc_state_updates_needed",
            "execution_commands",
            "evidence_summary",
            "missing_retention",
        ],
        "recommended_when": "Before deleting or preserving a completed downstream agent worktree.",
    },
    {
        "name": "run_context.py",
        "purpose": "Read one run/job record with monitor and stop details.",
        "mutating": False,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": False,
        "supports_compact": True,
        "primary_target": "--id",
        "fields_supported": [
            "run_id",
            "status",
            "experiment_id",
            "monitor_command",
            "stop_command",
            "progress_file",
            "resources",
            "output_retention",
        ],
        "recommended_when": "Monitor or stop a known long-running execution.",
    },
    {
        "name": "record_gate_result.py",
        "purpose": "Write a standard gate_result.json file and attach it to an experiment or run.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "supports_show_diff": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "gate_id",
            "experiment_id",
            "run_id",
            "gate_type",
            "passed",
            "expected",
            "observed",
            "fatal_failures",
            "preflight",
            "warnings",
            "next_allowed_action",
            "artifact_id",
            "gate_result_file",
        ],
        "recommended_when": "Record the result of a dataset, cache, smoke, training, evaluation, or preflight gate.",
    },
    {
        "name": "ingest_gate_result.py",
        "purpose": "Attach an existing gate_result.json file to an experiment or run.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "supports_show_diff": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "gate_id",
            "gate_result_file",
            "experiment_id",
            "run_id",
            "artifact_id",
        ],
        "recommended_when": "Link a gate file produced by a launcher, artifact bundle, or worktree output.",
    },
    {
        "name": "report_option_workstream.py",
        "purpose": "Write an option workstream report with recommendation and evidence summary.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Return findings from an option-following agent to the upstream problem.",
    },
    {
        "name": "finalize_workstream.py",
        "purpose": "Finalize one option workstream by explicitly updating option/problem/stage state, report, artifacts, and optional coordinator focus actions.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "fields_supported": ["option.status", "problem.status", "stage.status", "workstream_report", "linked_artifacts", "coordinator/current_state.next_actions"],
        **file_schema_for_script("finalize_workstream.py"),
        "path_resolution": "In --file input, relative summary_file resolves against the finalize file directory, then the data root, then cwd.",
        "recommended_when": "Close out an option workstream after experiments have been recorded.",
    },
    {
        "name": "import_worktree_findings.py",
        "purpose": "Import safe evidence changes from a worktree-local Research Cockpit root into the canonical root.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["artifact nodes", "experiment findings", "result_summary", "next_actions", "workstream_report"],
        "recommended_when": "Recover findings when an agent accidentally wrote evidence into a worktree-local cockpit root.",
    },
    {
        "name": "ingest_artifact.py",
        "purpose": "Copy run output into the canonical store; experiment targets create an artifact record by default.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": [
            "--node",
            "--from",
            "--run-id",
            "--id",
            "--title",
            "--summary",
            "--agent",
            "--link",
            *ASSIGNMENT_SCOPE_FLAGS,
            "--record-only",
            "--promote",
            "--promotion-reason",
        ],
        "fields_supported": [
            "node",
            "from",
            "run_id",
            "artifact_id",
            "mode",
            "promotion_reason",
            "path",
            "links",
            "agent",
        ],
        "recommended_when": "Preserve ordinary experiment output as a lightweight record; use --promote with a reason only for durable graph evidence.",
    },
    {
        "name": "list_artifact_records.py",
        "purpose": "List record-only artifact evidence without creating or loading graph artifact nodes.",
        "mutating": False,
        "supports_json": True,
        "supports_compact": True,
        "extra_supported_flags": ["--experiment", "--id", "--run-id", "--status"],
        "fields_supported": ["artifact_records", "experiment_id", "run_id", "status", "promoted_artifact_id", "retention"],
        "recommended_when": "Inspect record-only run outputs before deciding whether to promote them to graph artifacts.",
    },
    {
        "name": "promote_artifact_record.py",
        "purpose": "Promote one record-only artifact evidence item into a graph artifact node and write back the promotion marker.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": [
            "--id",
            "--artifact-id",
            "--link-to",
            "--promotion-reason",
            *ASSIGNMENT_SCOPE_FLAGS,
        ],
        "fields_supported": [
            "artifact_records",
            "artifact_id",
            "linked_artifacts",
            "promoted_artifact_id",
            "promotion_reason",
        ],
        "recommended_when": "Promote record-only evidence only when it must become long-lived graph evidence for navigation, decisions, or baselines.",
    },
    {
        "name": "compact_artifacts.py",
        "purpose": "Classify graph artifact nodes and explicitly demote can_demote run outputs into artifact records without deleting payload files.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_show_diff": True,
        "extra_supported_flags": ["--id", "--execute", "--no-build"],
        "fields_supported": ["artifact_demotions", "artifact_records", "linked_artifact_records", "migration_report", "retention", "linked_artifacts", "classification"],
        "recommended_when": "Dry-run audit graph artifact growth first; execute only a single can_demote artifact when demotion is intentional.",
    },
    {
        "name": "record_finding.py",
        "purpose": "Append a structured finding to an experiment.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "statement",
            "confidence",
            "outcome",
            "metrics",
            "linked_artifacts",
            "result_summary",
            "evidence_path",
            "evidence_links",
        ],
        "recommended_when": "Record evidence after an experiment finishes.",
    },
    {
        "name": "update_finding.py",
        "purpose": "Update an existing experiment finding without hand-editing YAML.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": ["statement", "confidence", "outcome", "metrics", "linked_artifacts"],
        "recommended_when": "Revise a finding statement or attach artifact evidence after initial recording.",
    },
    {
        "name": "create_artifact.py",
        "purpose": "Create an artifact node with path/links and optionally link it to existing nodes.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ["--file", "--print-schema", *ASSIGNMENT_SCOPE_FLAGS],
        "fields_supported": [
            "title",
            "status",
            "summary",
            "path",
            "links",
            "linked_artifacts",
            "artifact_kind",
            "retention",
        ],
        **file_schema_for_script("create_artifact.py"),
        "recommended_when": "Record experiment result folders, review bundles, metrics directories, or other evidence artifacts.",
    },
    {
        "name": "link_artifact.py",
        "purpose": "Link an existing artifact to nodes and update artifact path/links.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": ["path", "links", "linked_artifacts"],
        "recommended_when": "Attach existing artifact evidence to experiments, options, problems, or decisions.",
    },
    {
        "name": "complete_experiment.py",
        "purpose": "Record a finding, mark an experiment done, and clear experiment-local next actions.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "finding",
            "confidence",
            "outcome",
            "metrics",
            "artifact_ids",
            "result_summary",
            "evidence_path",
            "evidence_links",
        ],
        "recommended_when": "Conservatively complete an experiment without changing option, problem, or focus state.",
    },
    {
        "name": "close_current_experiment.py",
        "purpose": "Complete an experiment and explicitly move global and/or agent focus.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": False,
        "supports_no_build": True,
        "supports_compact": True,
        "fields_supported": ["finding", "confidence", "outcome", "artifact_ids", "result_summary", "next_focus", "sync_agent"],
        "recommended_when": "Close the current experiment and advance focus in one explicit workflow.",
    },
    {
        "name": "complete_experiments.py",
        "purpose": "Batch complete several experiments from a YAML findings file.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "can_batch": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "defaults",
            "experiments",
            "finding",
            "confidence",
            "outcome",
            "metrics",
            "artifact_ids",
            "result_summary",
            "evidence.path",
            "evidence.links",
        ],
        **file_schema_for_script("complete_experiments.py"),
        "recommended_when": "Close a sweep or multi-backend experiment set without repeated rebuilds.",
    },
    {
        "name": "create_followup_experiment.py",
        "purpose": "Create a follow-up experiment derived from an existing experiment.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "status=queued",
            "derived_from",
            "parent",
            "title",
            "priority",
            "success_criteria",
            "next_actions",
            "coordinator_set_focus",
        ],
        "hierarchy_guidance": (
            "Use only for a single queued gate under an existing option. "
            "Use create-workstream for multi-step or worktree-derived child branches. "
            "Assignment-scoped workers should pass --assignment and then use set-cursor; --set-focus is coordinator/global only."
        ),
        "recommended_when": "Branch a done or running experiment into the next queued optimization gate.",
    },
    {
        "name": "migrate_terminal_next_actions.py",
        "purpose": "Move live next_actions off terminal nodes into an explicit follow-up path.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ASSIGNMENT_SCOPE_FLAGS,
        "fields_supported": [
            "terminal next_actions",
            "single followup experiment",
            "derived_from",
            "clear source next_actions",
            "create-workstream guidance",
        ],
        "hierarchy_guidance": (
            "Use for one queued follow-up gate from a done experiment. "
            "Use create-workstream for multi-step cleanup or non-experiment terminal nodes."
        ),
        "recommended_when": "Clean up stale next_actions reported on done or otherwise terminal nodes.",
    },
    {
        "name": "promote_decision.py",
        "purpose": "Create a decision from an option and optional evidence.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Create a proposed or accepted decision from an option.",
    },
    {
        "name": "update_decision_evidence.py",
        "purpose": "Refresh structured evidence fields for an existing decision.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["supporting_experiments", "evidence_strength", "evidence_summary"],
        "recommended_when": "Update evidence before reviewing a proposed decision.",
    },
    {
        "name": "update_decision_checklist.py",
        "purpose": "Append checklist metadata for an existing decision without changing decision status.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["alternatives_considered", "consequences", "next_required_actions", "evidence_summary"],
        "recommended_when": "Fill alternatives, consequences, and next actions before accepting a decision.",
    },
    {
        "name": "accept_decision.py",
        "purpose": "Accept an existing decision and sync parent option/problem state.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Accept a decision after checklist passes.",
    },
    {
        "name": "set_baseline.py",
        "purpose": "Set or clear the default baseline that a node and its descendants should inherit.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["baseline.option", "baseline.decision", "baseline.artifacts", "baseline.reason"],
        "recommended_when": "Choose the default baseline for follow-up agents without expanding all accepted history.",
    },
    {
        "name": "update_node_fields.py",
        "purpose": "Update supported structured node fields without hand-editing YAML.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "extra_supported_flags": ["--metadata-file", *ASSIGNMENT_SCOPE_FLAGS],
        "fields_supported": supported_field_names(),
        "recommended_when": "Update supported node fields without hand-editing YAML.",
    },
    {
        "name": "update_workstream_fields.py",
        "purpose": "Update safe option agent_workstream fields without hand-editing YAML.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "supports_compact": True,
        "fields_supported": [
            "agent_workstream.status",
            "agent_workstream.objective",
            "agent_workstream.owner",
            "agent_workstream.session_id",
            "agent_workstream.report_to_problem",
        ],
        "recommended_when": "Adjust nested option workstream metadata safely.",
    },
    {
        "name": "apply_suggestion.py",
        "purpose": "Queue an action suggestion into current_state or the source node.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Turn a suggestion into an explicit next action.",
    },
    {
        "name": "update_suggestion_state.py",
        "purpose": "Mark a suggestion active, dismissed, or completed.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "fields_supported": ["suggestion_lifecycle"],
        "recommended_when": "Hide or restore action suggestions.",
    },
    {
        "name": "cleanup_suggestion_lifecycle.py",
        "purpose": "Remove orphan suggestion lifecycle records.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Clean stale lifecycle history after reviewing Data Health.",
    },
    {
        "name": "create_note.py",
        "purpose": "Create and link a Markdown note for a supported node.",
        "mutating": True,
        "supports_json": True,
        "supports_dry_run": True,
        "supports_no_build": True,
        "recommended_when": "Create long-form notes for problem, option, experiment, or decision nodes.",
    },
]


PROGRESS_COMMAND_SCRIPTS = {
    "build_dashboard.py",
    "complete_run.py",
    "context.py",
    "ingest_artifact.py",
    "ingest_gate_result.py",
    "node_context.py",
    "record_finding.py",
    "update_node_fields.py",
    "update_run.py",
    "validate_cockpit.py",
}

DISCOVERY_FLAGS = {
    "--compact": "supports_compact",
    "--dry-run": "supports_dry_run",
    "--json": "supports_json",
    "--no-build": "supports_no_build",
    "--show-diff": "supports_show_diff",
}


def _flag_support(row: dict[str, object]) -> tuple[list[str], list[str]]:
    supported: list[str] = [str(flag) for flag in row.get("extra_supported_flags", [])]
    unsupported: list[str] = []
    command_name = str(row.get("name") or "")
    if command_name in PROGRESS_COMMAND_SCRIPTS or (
        bool(row.get("mutating")) and command_name.endswith(".py")
    ):
        supported.append("--progress")
    if bool(row.get("supports_root", True)):
        supported.append("--root")
    else:
        unsupported.append("--root")
    for flag, field in DISCOVERY_FLAGS.items():
        if bool(row.get(field)):
            supported.append(flag)
        else:
            unsupported.append(flag)
    if bool(row.get("supports_watch")):
        supported.extend(["--watch", "--interval", "--max-iterations"])
    if bool(row.get("supports_profile")):
        supported.extend(["--profile", "--profile-output"])
    return sorted(supported), sorted(unsupported)


def _input_modes(row: dict[str, object], supported_flags: list[str]) -> list[str]:
    modes = ["flags"]
    if row.get("file_schema") or any(flag == "--file" or flag.endswith("-file") for flag in supported_flags):
        modes.append("file")
    if row.get("schema_command"):
        modes.append("schema")
    return modes


def _batch_policy(
    *,
    mutating: bool,
    supports_no_build: bool,
    writes_truth_source: bool,
    writes_generated_files: bool,
) -> dict[str, object]:
    if not mutating:
        mode = "read_only"
    elif supports_no_build and writes_truth_source:
        mode = "serial_no_build"
    elif writes_generated_files and not writes_truth_source:
        mode = "generated_build"
    else:
        mode = "single_mutation"
    serial_no_build = mode == "serial_no_build"
    return {
        "mode": mode,
        "use_no_build": bool(supports_no_build and writes_truth_source),
        "serial_required": bool(mutating),
        "finish_commands": [],
        "worker_verify_commands": BATCH_WORKER_VERIFY_COMMANDS if serial_no_build else [],
        "final_handoff_commands": BATCH_FINAL_HANDOFF_COMMANDS if serial_no_build else [],
    }


def agent_command_manifest(
    *,
    compact: bool = False,
    summary_only: bool = False,
    name: str | None = None,
    workflow: str | None = None,
    group: str | None = None,
    status: str | None = None,
    deprecated: bool = False,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for command in COMMANDS:
        command_name = str(command["name"])
        subcommand = subcommand_for_script(command_name) if command_name.endswith(".py") else command_name
        if name and subcommand != name:
            continue
        mutating = bool(command["mutating"])
        supports_no_build = bool(command.get("supports_no_build"))
        required_flags = [str(flag) for flag in command.get("required_flags", [])]
        rebuild_default = bool(command.get("rebuild_default", mutating and supports_no_build))
        writes_truth_source = bool(command.get("writes_truth_source", mutating and command_name != "build_dashboard.py"))
        writes_generated_files = bool(
            command.get("writes_generated_files", rebuild_default or command.get("writes_dashboard", False))
        )
        row = {
            **command,
            "name": subcommand,
            "canonical_name": str(command.get("canonical_name", subcommand)),
            "group": command_group_for_command(subcommand),
            "status": str(command.get("status", "active")),
            "aliases": [*list(command.get("aliases", [])), *grouped_aliases_for_command(subcommand)],
            "replacement": command.get("replacement"),
            "capability_file": CAPABILITY_BY_COMMAND[command_name],
            "command": " ".join(["research-cockpit", subcommand, *required_flags]),
            "python_module_command": " ".join(
                ["python", "-m", "research_cockpit.cli", subcommand, *required_flags]
            ),
            "cwd": "research_repo_root",
            "writes_truth_source": writes_truth_source,
            "writes_generated_files": writes_generated_files,
            "can_batch": bool(command.get("can_batch", supports_no_build)),
            "batch_policy": _batch_policy(
                mutating=mutating,
                supports_no_build=supports_no_build,
                writes_truth_source=writes_truth_source,
                writes_generated_files=writes_generated_files,
            ),
            "requires_serial_mutation": mutating,
            "conflict_policy": CONFLICT_POLICY if mutating else "",
            "safe_in_plan_mode": bool(command.get("safe_in_plan_mode", not mutating)),
            "rebuild_default": rebuild_default,
            "fields_supported": command.get("fields_supported", []),
            "workflow_tags": WORKFLOW_TAGS_BY_COMMAND.get(subcommand, []),
            "lifecycle": command_lifecycle_for_command(subcommand, mutating=mutating),
            "supports_show_diff": subcommand in SHOW_DIFF_COMMANDS,
            "supports_root": bool(command.get("supports_root", True)),
        }
        supported_flags, unsupported_flags = _flag_support({**row, "name": command_name})
        row.pop("extra_supported_flags", None)
        row["supported_flags"] = supported_flags
        row["unsupported_flags"] = unsupported_flags
        row["input_modes"] = _input_modes(row, supported_flags)
        if workflow and workflow not in row["workflow_tags"]:
            continue
        if group and row["group"] != group:
            continue
        if status and row["status"] != status:
            continue
        if deprecated and row["status"] == "active":
            continue
        if summary_only:
            batch_policy = row.get("batch_policy")
            row["batch_policy_mode"] = (
                str(batch_policy.get("mode") or "") if isinstance(batch_policy, dict) else ""
            )
            row = {key: value for key, value in row.items() if key in SUMMARY_COMMAND_KEYS}
        elif compact:
            row = {key: value for key, value in row.items() if key in COMPACT_COMMAND_KEYS}
        rows.append(row)
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true", help="Print machine-readable command manifest")
    parser.add_argument("--compact", action="store_true", help="Print a short agent discovery payload.")
    parser.add_argument("--summary-only", action="store_true", help="Print minimal command selection fields.")
    parser.add_argument("--name", help="Return only one command by subcommand name.")
    parser.add_argument("--workflow", choices=WORKFLOW_CHOICES, help="Return commands tagged for one workflow.")
    parser.add_argument("--group", choices=GROUP_CHOICES, help="Return commands in one canonical command group.")
    parser.add_argument("--status", choices=STATUS_CHOICES, help="Return commands with one lifecycle status.")
    parser.add_argument(
        "--deprecated",
        action="store_true",
        help="Return only compatibility or deprecated commands.",
    )
    args = parser.parse_args()
    if args.status and args.deprecated:
        parser.error("--status and --deprecated cannot be combined")

    commands = agent_command_manifest(
        compact=args.compact,
        summary_only=args.summary_only,
        name=args.name,
        workflow=args.workflow,
        group=args.group,
        status=args.status,
        deprecated=args.deprecated,
    )
    if args.json:
        emit_json({"commands": commands}, compact=args.summary_only)
        return

    for command in commands:
        marker = "write" if command["mutating"] else "read"
        print(f"{command['name']} [{marker}]: {command['purpose']}")
        print(f"  {command['command']}")


if __name__ == "__main__":
    main()
